### ISSUE TITLE
Randomly not working on OSX, not sure why

### ISSUE THREAD

**Issue by mbigras** [clvv/fasd#102]
I just installed `fasd` with `brew` it was working for about an hour, and now it's randomly broken. I'm not sure why, below is and example of me trying to get `fasd` to work. It's weird because both the version and the help options are working but nothing else

    ➜  ~  ls | grep dir
    anotherdir
    somedir
    ➜  ~  cd somedir
    ➜  ~/somedir  ..
    ➜  ~  z somedir
    ➜  ~  touch somedir/somefile
    ➜  ~  vim somedir/somefile
    ➜  ~  f somefile
    ➜  ~  fasd -d some
    ➜  ~  echo $?
    0
    ➜  ~  z some
    ➜  ~  echo $?
    0
    ➜  ~  fasd -h
    fasd [options] [query ...]
    [f|a|s|d|z] [opions] [query ...]
      options:
        -s         list paths with scores
        -l         list paths without scores
        -i         interactive mode
        -e <cmd>   set command to execute on the result file
        -b <name>  only use <name> backend
        -B <name>  add additional backend <name>
        -a         match files and directories
        -d         match directories only
        -f         match files only
        -r         match by rank only
        -t         match by recent access only
        -R         reverse listing order
        -h         show a brief help message
        -[0-9]     select the nth entry

    fasd [-A|-D] [paths ...]
        -A    add paths
        -D    delete paths
    ➜  ~  which fasd
    /usr/local/bin/fasd
    ➜  ~  fasd --version
    1.0.1

Also below is my system info and `.zshrc`:
[sist](https://github.com/dawsonbotsford/sist) output:

### shell
`uname`: Darwin
`echo $SHELL`: /bin/zsh
`echo $TERM`: xterm-256color
`echo $TERM_PROGRAM`: iTerm.app

Time created: Mon Oct 24 2016 01:22:43 GMT-0700 (PDT)

    #
    # User configuration sourced by interactive shells
    #

    # Source zim
    if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
      source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
    fi

    # hello world 2016-10-24T05:11:51
    alias config='/usr/local/bin/git --git-dir=/Users/max/.dotfiles/ --work-tree=/Users/max'

    #-------------------
    # fasd
    # https://github.com/clvv/fasd
    # randomly broken
    #
    #-------------------
    # fasd_cache="$HOME/.fasd-init-zsh"
    # if [ "$(command -v fasd)" -nt "$fasd_cache" -o ! -s "$fasd_cache" ]; then
    #   fasd --init posix-alias zsh-hook zsh-ccomp zsh-ccomp-install zsh-wcomp zsh-wcomp-install >| "$fasd_cache"
    # fi
    # source "$fasd_cache"
    # unset fasd_cache
    eval "$(fasd --init auto)"

    alias v='f -e vim'
    #-------------------

**Comment by kaliberr44** [comment]
I have the same problem - but that might be connected with Zim (as I see you are sourcing it).

Try to run zim_clean_cache from .zim/tools. The restart your terminal - fasd should work.
But if you run another zsh subshell, or restart again fasd will do nothing (no logs either).

**Comment by jcrben** [comment]
@mbigras it is usually helpful if you can provide a resolution path when closing
