### ISSUE TITLE
Consider adding a "parent dir" mode

### ISSUE THREAD

**Issue by yacoob** [clvv/fasd#118]
As I understand, `fasd` collects `$PWD` and arguments of commands. This means, if I have visited a particular directory, I can later quickly recall it:

```
$ s Profiles
/Users/yacoob/Library/Application Support/iTerm2/DynamicProfiles
```

Every now and then, I need to recall a particular *parent* of a directory I've visted. In the example above, I'd like to get to `~/Library/Application Support/iTerm2`, but given that I've never actually visited it with `fasd` on, `fasd` can't find it.

```
$ s iTerm2
2       2.41181    /Users/yacoob/Library/Preferences/com.googlecode.iterm2.plist
1       4.15924    /Users/yacoob/workarea/conf/osx/plists/com.googlecode.iterm2.plist
> ^C
$ cd ~/Library/Application\ Support/iTerm2
$ cd
$ s iTerm2
/Users/yacoob/Library/Application Support/iTerm2
```

Maybe add it as a fallback before fuzzy search?
Note: I'm only starting with `fasd`, so it's quite possible I'm missing something fundamental in the way this has been designed to work.

Thanks for considering!

**Comment by nhooyr** [comment]
Its easiest if you just delete whats after till you get the directory. How would this proposed parent dir mode work anyway?
