### ISSUE TITLE
Using spotlight backend

### ISSUE THREAD

**Issue by yb66** [clvv/fasd#121]
Hi,

I'm not clear on how to use the Spotlight backend. Do I have to add something to the .fasdrc or should I use the `-b` option? I've read the readme and the man page but none of the myriad ways I've tried running the command bring back any results. Running the mdfind command directly does so I'm a bit stumped.

Any help with this will be much appreciated, and thanks for writing a really helpful tool!

Regards.
iain

**Comment by clvv** [comment]
Make sure you have the latest git version. The spotlight backend never made it into a release (yet).

**Comment by yb66** [comment]
@clvv And then put \`spotlight` in the ~/.fasdrc?

**Comment by wendelscardua** [comment]
@yb66 (I may be too late, but...) It should be something like this (on `~/.fasdrc`):
```sh
_FASD_BACKENDS="spotlight"
```

**Comment by yb66** [comment]
@wendelscardua No, that's very helpful, thanks :)
