### ISSUE TITLE
Change or disable aliases

### ISSUE THREAD

**Issue by mrbig033** [clvv/fasd#125]
I have other aliases mapped to some of the fasd default, and I'd like to change or disable some of those in order to keep my system sane. How can I do that?

**Comment by mrbig033** [comment]
Answering my own question: just edit ~/.fasd-init-bash. The syntax is the same as `.bashrc` or `.bash_aliases`.

**Comment by hi-hai** [comment]
I didn't see `~/.fasd-init-bash` file.
