### ISSUE TITLE
very slow on cygwin.

### ISSUE THREAD

**Issue by mijoharas** [clvv/fasd#39]
First off, thanks for making this, massive timesaver.

Unfortunately I've needed to use windows for work and thus naturally I've setup cygwin and fasd in order to be actually productive. The problem is that eval-ing fasd adds an extra 3-4 seconds to the prompt loading on every command making things nearly unusable. Now obviously this isn't a problem that's immediately (or possibly at all) your fault, but I thought I'd open an issue to try and figure out a way to make this work on cygwin.

**Comment by avimar** [comment]
Eh, how did you get fasd to install in cygwin or MSYS-git ?

**Comment by mijoharas** [comment]
I can't really remember, but I think I just built it from source [as here](https://github.com/clvv/fasd#install). I can double check when I get to my windows machine. (also yes, this was on cygwin).

**Comment by dsutic** [comment]
Same for me. uname gives CYGWIN_NT-6.3-WOW and I've installed fasd 1.0.1 manually (make install). Every bash command takes seconds to complete, even an empty line
