### ISSUE TITLE
How to disable certain aliases?

### ISSUE THREAD

**Issue by callumlocke** [clvv/fasd#48]
I just have `eval "$(fasd --init auto)"` in my `.bash_profile`, and this seems to set up all the standard Fasd aliases. But some of those aliases (like `s`) I want to use for other commands.

Even if I declare a new `alias` after the Fasd initialisation line, the `s` alias always gets overtaken by Fasd somehow.

Is there a way I can restrict which aliases Fasd creates?

(Sorry I couldn't figure this out from the docs.)

**Comment by clvv** [comment]
If you are using Bash, `fasd --init auto` actually redirect to `fasd --init posix-alias bash-hook bash-ccomp bash-ccomp-install`. You can remove posix-alias argument so fasd will not load the default aliases. Then you can just cherry-pick what aliases you want from what `fasd --init posix-alias` returns, which is the following:
```
alias a='fasd -a'
alias s='fasd -si'
alias sd='fasd -sid'
alias sf='fasd -sif'
alias d='fasd -d'
alias f='fasd -f'
# function to execute built-in cd
fasd_cd() {
  if [ $# -le 1 ]; then
    fasd "$@"
  else
    local _fasd_ret="$(fasd -e 'printf %s' "$@")"
    [ -z "$_fasd_ret" ] && return
    [ -d "$_fasd_ret" ] && cd "$_fasd_ret" || printf %s\n "$_fasd_ret"
  fi
}
alias z='fasd_cd -d'
alias zz='fasd_cd -d -i'
```
