### ISSUE TITLE
How can I differentiate paths which only differ in one prefix directory?

### ISSUE THREAD

**Issue by alicee** [clvv/fasd#53]
Let's say I frequently access the following directories:

`/src/one/two/three/`
`/srctests/one/two/three/`

Now `z src three` kind of randomly (to the naive user) decides whether to go into the actual src or the test directory. Is there something along the lines of `z src/ three` to inform fasd that src is to be treated as its own prefix directory?

Renaming isn't possible, I'm afraid.

**Comment by clvv** [comment]
Yes. Your intuition, `z src/ three`, should works. Just append `/`!

**Comment by alicee** [comment]
It works :) Sorry, it appears I hadn't populated enough paths for it to recognize that prefix yet.
