### ISSUE TITLE
Not working on particular machine

### ISSUE THREAD

**Issue by jcrben** [clvv/fasd#69]
Hi - I have this working quite nicely on a personal Macbook Pro, but I can't seem to get it working on my work Macbook Pro. Wish I had a more descriptive issue title.

I enabled the FASD_SINK error log which looks currently like this (nothing seems to be further written to it):
````
complete -F _fasd_bash_cmd_complete a
complete -F _fasd_bash_cmd_complete d
complete -o nospace -S '/' -X '*/' -F _cdargs_aliases cdb
complete -F _fasd_bash_cmd_complete f
complete -F _fasd_bash_cmd_complete fasd
complete -F _fasd_bash_cmd_complete sd
complete -F _fasd_bash_cmd_complete sf
complete -o nospace -S '/' -X '*/' -F _cdargs_aliases cv
complete -F _fasd_bash_cmd_complete s
complete -F _fasd_bash_cmd_complete zz
complete -F _fasd_bash_cmd_complete z
complete -o nospace -S '/' -X '*/' -F _cdargs_aliases cb
complete -F _fasd_bash_cmd_complete a
complete -F _fasd_bash_cmd_complete d
complete -o nospace -S '/' -X '*/' -F _cdargs_aliases cdb
complete -F _fasd_bash_cmd_complete f
complete -F _fasd_bash_cmd_complete fasd
complete -F _fasd_bash_cmd_complete sd
complete -F _fasd_bash_cmd_complete sf
complete -o nospace -S '/' -X '*/' -F _cdargs_aliases cv
complete -F _fasd_bash_cmd_complete s
complete -F _fasd_bash_cmd_complete zz
complete -F _fasd_bash_cmd_complete z
complete -o nospace -S '/' -X '*/' -F _cdargs_aliases cb
````

I also added some print statements to try to figure out what was happening as well. `fasd_cd()` seemed as good a place as any. To do this I switched to sourcing rather than evaling fasd (installed to /usr/local/bin/fasd using homebrew) in my bashrc.

When fasd_cd is run through the z alias, `_fasd_ret="\$(fasd -e 'printf %s' "\$@")"` is evaluating to to an empty string. However, if I print out `$@`, I get `posix-alias bash-hook bash-ccomp bash-ccomp-install` which is a bit surprising given that I'm running z with just a directory...

**Comment by clvv** [comment]
This is indeed an odd issue. What's your script and login shell? Are there environmental variables that start with `_FASD_` that might be tempering with `fasd`? I'm guessing it's probably not a bug of the code itself rather than the environment it is being ran on.

**Comment by Eisfreak7** [comment]
I'm not entirely sure, but I think I have the same issue.
Fasd works without any problems on my desktop pc.
On my ThinkPad however, it doesn't do anything. It creates the weighted list of files (just typing 'fasd' correctly gives this list), but it doesn't do anything with it.
```
  fasd_cd -d <something>
```
does nothing.
```
  fasd_cd -d -i
```
followed by a seleciton prints the selection, but doesnt change the directory.
I'm using zsh with the exact same configuration as my desktop.

**Comment by jcrben** [comment]
Oddly enough, I tried this again today and it worked. So I'm closing this. If I ever figure out why it happened, I'll drop a note here.
