### ISSUE TITLE
[suggestion] make z (fasd -d) cycle matches automatically

### ISSUE THREAD

**Issue by oranja** [clvv/fasd#78]
I was using _autojump_ and totally enjoying it, but thought that moving to _fasd_ might unleash even more shell power. Well, _fasd_ is great but it's missing a feature from _autojump_, which in my opinion is essential to any product in this category.

Let's say that I have two folders, one is `/george/safford/parker` and the second is `/charlie/parker`.
I could use `z s parker` for the first and `z c parker` for the second, but most of the time I'm just using `z parker` and it takes me straight to the one I use most frecently - `/charlie/parker`. All is well, except, every now and then, I want the second folder instead, and let's say I'm already inside `/charlie/parker` (either because I was just working there or I went there by the force of habit). In this case, `z parker` will never take me to `/george/safford/parker`, and IMHO, that's a shame.

With `autojump`, if there is more than one match to the user's pattern, and she is already parked in one of these matches, `j` will automatically cycle to the next match and jump there instead.

Any chance implementing something like this for `fasd`'s `z`?

(If I will find some time, I will try to see what it takes and submit a PR myself, but that's a big if :disappointed: )

**Comment by clvv** [comment]
This can be done right now with a custom z function if you dig hard enough--it amounts to using fasd to list entries by score and removing the $PWD. All shouldn't take more than ~10-15 lines of code.
