### ISSUE TITLE
Paths not being added to history

### ISSUE THREAD

**Issue by jwhitmarsh** [clvv/fasd#84]
Unless I run `eval "$(fasd --init auto)"` directly in the terminal, paths I `cd` to are not being added to `~/.fasd`. Having `eval "$(fasd --init auto)"` in the bashrc doesn't seem to work.

OSX 10.11.3
awk version 20070501
I cannot for the life of me find out (or google how to find out) my sed version - it's whatever ships with El Capitain

here's bit of `~/.fasd.log`

```
/usr/local/bin/fasd: line 61: original-awk: command not found
/usr/local/bin/fasd: line 61: nawk: command not found
/usr/local/bin/fasd: line 61: mawk: command not found
/usr/local/bin/fasd: line 61: gawk: command not found
/usr/local/bin/fasd: line 61: original-awk: command not found
/usr/local/bin/fasd: line 61: nawk: command not found
/usr/local/bin/fasd: line 61: mawk: command not found
/usr/local/bin/fasd: line 61: gawk: command not found
/usr/local/bin/fasd: line 61: original-awk: command not found
/usr/local/bin/fasd: line 61: nawk: command not found
/usr/local/bin/fasd: line 61: mawk: command not found
/usr/local/bin/fasd: line 61: gawk: command not found
/usr/local/bin/fasd: line 61: original-awk: command not found
/usr/local/bin/fasd: line 61: nawk: command not found
/usr/local/bin/fasd: line 61: mawk: command not found
/usr/local/bin/fasd: line 61: gawk: command not found
/usr/local/bin/fasd: line 61: original-awk: command not found
/usr/local/bin/fasd: line 61: nawk: command not found
```

**Comment by SShrike** [comment]
> I cannot for the life of me find out (or google how to find out) my sed version

You tried `sed --version` right? Not sure about the BSD/OS X version, but on Linux the GNU sed provides a version string.

**Comment by jwhitmarsh** [comment]
Of course
```
:) 14:29 jwhitmarsh@BIC6588 ~/src/bcg-ui (master *% u=)
$ sed --version
sed: illegal option -- -
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]

:( 14:56 jwhitmarsh@BIC6588 ~/src/bcg-ui (master *% u=)
$ sed -v
sed: illegal option -- v
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
```

**Comment by SShrike** [comment]
Well that's curious behaviour.

**Comment by hashhar** [comment]
I had the same issue. In my case, moving the eval to the end of the bashrc fixed it. I'm trying to isolate the issue and so far it seems any change to any of the HISTFILE related variables after the eval causes fasd to go haywire.

**Comment by xin-jin** [comment]
I am having the same issue on one of my computers (while it works on other computers). No matter where I put `eval "$(fasd --init auto)"`, it just doesn't work unless I manually execute it in the terminal.

**Comment by JSpenced** [comment]
I am having this happen but nothing works. Did anyone figure out this issue?
